-- Grassdoor trust + growth foundation
begin;

create table if not exists public.venues (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  area text,
  nearest_station text,
  latitude double precision,
  longitude double precision,
  booking_url text,
  website_url text,
  constraint venues_latitude_check check (latitude is null or latitude between -90 and 90),
  constraint venues_longitude_check check (longitude is null or longitude between -180 and 180)
);

create unique index if not exists venues_name_area_unique
  on public.venues (lower(name), lower(coalesce(area, '')));

alter table public.dim_pitches
  add column if not exists venue_id bigint references public.venues(id) on delete set null,
  add column if not exists surface_type text,
  add column if not exists indoor boolean,
  add column if not exists changing_rooms boolean,
  add column if not exists parking boolean;

insert into public.venues (name, area, nearest_station, latitude, longitude)
select distinct p.name, p.area, p.nearest_station, p.latitude, p.longitude
from public.dim_pitches p
where not exists (
  select 1 from public.venues v
  where lower(v.name) = lower(p.name)
    and lower(coalesce(v.area, '')) = lower(coalesce(p.area, ''))
);

update public.dim_pitches p
set venue_id = v.id
from public.venues v
where p.venue_id is null
  and lower(v.name) = lower(p.name)
  and lower(coalesce(v.area, '')) = lower(coalesce(p.area, ''));

create index if not exists idx_dim_pitches_venue_id on public.dim_pitches (venue_id);

alter table public.fct_reviews
  add column if not exists moderation_status text not null default 'pending',
  add column if not exists reviewer_user_id uuid references auth.users(id) on delete set null,
  add column if not exists review_text text,
  add column if not exists would_book_again boolean,
  add column if not exists played_at date;

update public.fct_reviews
set moderation_status = 'approved'
where moderation_status = 'pending';

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'fct_reviews_moderation_status_check') then
    alter table public.fct_reviews add constraint fct_reviews_moderation_status_check
      check (moderation_status in ('pending', 'approved', 'rejected'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'fct_reviews_review_text_length_check') then
    alter table public.fct_reviews add constraint fct_reviews_review_text_length_check
      check (review_text is null or char_length(review_text) <= 1200);
  end if;
end $$;

create index if not exists idx_fct_reviews_moderation_status
  on public.fct_reviews (moderation_status, created_at desc);
create index if not exists idx_fct_reviews_reviewer_user
  on public.fct_reviews (reviewer_user_id)
  where reviewer_user_id is not null;

create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  event_name text not null,
  pitch_id bigint references public.dim_pitches(id) on delete set null,
  anonymous_session_id text,
  page_path text,
  destination_url text,
  metadata jsonb not null default '{}'::jsonb,
  constraint product_events_name_check check (
    event_name in ('pitch_view','booking_click','review_started','review_submitted','directory_search')
  ),
  constraint product_events_session_length_check check (
    anonymous_session_id is null or char_length(anonymous_session_id) <= 100
  )
);

create index if not exists idx_product_events_name_time
  on public.product_events (event_name, occurred_at desc);
create index if not exists idx_product_events_pitch_time
  on public.product_events (pitch_id, occurred_at desc)
  where pitch_id is not null;

alter table public.product_events enable row level security;
drop policy if exists "public can insert product events" on public.product_events;
create policy "public can insert product events"
on public.product_events for insert to anon, authenticated with check (true);
revoke select on public.product_events from anon, authenticated;
grant insert on public.product_events to anon, authenticated;

alter table public.venues enable row level security;
drop policy if exists "public can read venues" on public.venues;
create policy "public can read venues"
on public.venues for select to anon, authenticated using (true);
grant select on public.venues to anon, authenticated;

create or replace view warehouse.mart_review_moderation
with (security_invoker = true)
as
select moderation_status, count(*) as review_count,
       min(created_at) as oldest_review_at,
       max(created_at) as newest_review_at
from public.fct_reviews
group by moderation_status;

create or replace view warehouse.mart_product_funnel
with (security_invoker = true)
as
select
  date_trunc('day', occurred_at)::date as event_date,
  count(*) filter (where event_name = 'pitch_view') as pitch_views,
  count(*) filter (where event_name = 'booking_click') as booking_clicks,
  count(*) filter (where event_name = 'review_started') as review_starts,
  count(*) filter (where event_name = 'review_submitted') as reviews_submitted,
  count(distinct anonymous_session_id) as anonymous_sessions
from public.product_events
group by 1
order by 1;

create or replace view warehouse.mart_pitch_conversion
with (security_invoker = true)
as
select
  p.id as pitch_key,
  p.name,
  count(e.id) filter (where e.event_name = 'pitch_view') as pitch_views,
  count(e.id) filter (where e.event_name = 'booking_click') as booking_clicks,
  count(e.id) filter (where e.event_name = 'review_started') as review_starts,
  count(e.id) filter (where e.event_name = 'review_submitted') as review_submissions
from public.dim_pitches p
left join public.product_events e on e.pitch_id = p.id
group by p.id, p.name;

commit;
